CREATE TABLE "report" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"channel_id" int,
	"category_id" int,
	"bank_id" int,
	"state_id" int,
	"urban_or_rural" varchar(50),
	"loss_amount" decimal(10,2),
	"fraud_date" date,
	"description" text,
	"report_date" timestamp,
	"was_victim" boolean
);
	
CREATE TABLE "aftermath" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"report_id" int,
	"reported_to_bank" boolean,
	"reported_to_police" boolean,
	"recovered_amount" decimal(10,2),
	"resolved" boolean
);
	
CREATE TABLE "bank" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(100),
	"digital_only" boolean
);
	
CREATE TABLE "state" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"state" varchar(50),
	"region" varchar(50)
);
	
CREATE TABLE "fraud_channel" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(100)
);
	
CREATE TABLE "fraud_category" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" varchar(100),
	"description" text
);
	
ALTER TABLE "report" ADD FOREIGN KEY ("channel_id") REFERENCES "fraud_channel" ("id");
	
ALTER TABLE "report" ADD FOREIGN KEY ("category_id") REFERENCES "fraud_category" ("id");
	
ALTER TABLE "report" ADD FOREIGN KEY ("bank_id") REFERENCES "bank" ("id");
	
ALTER TABLE "report" ADD FOREIGN KEY ("state_id") REFERENCES "state" ("id");
	
ALTER TABLE "aftermath" ADD FOREIGN KEY ("report_id") REFERENCES "report" ("id");
	
	